version: '3.8'
services:
  db:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports: 
      - "27017:27017"  
  web: 
    container_name: app_server
    # '.' represents the current directory in which docker-compose.yml is present.
    # and this specifies the location of our Dockerfile
    build: .
    volumes: 
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      MONGODB_CONNSTRING: mongodb://mongodb:27017/setGetServer
      
# volumes:
#   node_modules:
